# Generated by Django 2.2.10 on 2020-06-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='必填', max_length=255, unique=True, verbose_name='年级名称')),
                ('begin_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='结束时间')),
                ('status', models.SmallIntegerField(choices=[(0, '之前学年'), (1, '当前学年'), (2, '未来学年')], help_text='必填', verbose_name='学年状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '入学学年表',
                'verbose_name_plural': '入学学年表',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='必填', max_length=32, unique=True, verbose_name='院校')),
                ('logo', models.CharField(help_text='必填', max_length=255, verbose_name='LOGO')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Organization', to_field='name')),
            ],
            options={
                'verbose_name': '学校表',
                'verbose_name_plural': '学校表',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='必填', max_length=32, unique=True, verbose_name='站点名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Organization', to_field='name')),
                ('schools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SchoolInfo', to_field='title')),
            ],
            options={
                'verbose_name': '站点表',
                'verbose_name_plural': '站点表',
            },
        ),
        migrations.CreateModel(
            name='TrainTypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='必填', max_length=32, unique=True, verbose_name='培养类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '培养类型',
                'verbose_name_plural': '培养类型',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], help_text='必填', verbose_name='性别')),
                ('nation', models.CharField(default='汉族', help_text='必填', max_length=32, verbose_name='民族')),
                ('birth_place', models.CharField(default='身份证上:xx省xx市', help_text='必填', max_length=64, verbose_name='籍贯')),
                ('identity_num', models.CharField(help_text='必填', max_length=18, verbose_name='身份证号')),
                ('address', models.CharField(help_text='必填', max_length=128, verbose_name='常用住址')),
                ('tel', models.CharField(help_text='必填', max_length=11, verbose_name='联系电话1')),
                ('tel_2', models.CharField(blank=True, help_text='选填', max_length=11, null=True, verbose_name='联系电话2')),
                ('majors', models.CharField(help_text='必填', max_length=64, verbose_name='报读专业')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student_status', models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核拒绝')], default=0)),
                ('memo', models.CharField(blank=True, help_text='选填', max_length=128, null=True, verbose_name='备注')),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.GradeInfo', to_field='title', verbose_name='入学学年')),
                ('sites', models.ForeignKey(help_text='必填', on_delete=django.db.models.deletion.CASCADE, to='crm.SiteInfo', to_field='title', verbose_name='招生站点')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
            },
        ),
        migrations.AddField(
            model_name='gradeinfo',
            name='schools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SchoolInfo', to_field='title'),
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, verbose_name='键')),
                ('value', models.CharField(max_length=80, verbose_name='值')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='crm.Dict')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
            },
        ),
    ]
